lahcen = ex04

CXX      = c++

CXXFLAGS = -Wall -Wextra -Werror -std=c++98  

SRC  = main.cpp 

OBJ = $(SRC:.cpp=.o)

%.o: %.c $(SRC)
	$(CXX) -c -o   $@ $< $(CFLAGS)

all: $(lahcen)

$(lahcen): $(OBJ)
	$(CXX) $(CXXFLAGS)  -fsanitize=address -g3 $(OBJ) -o $(lahcen)

clean:
	rm -f $(OBJ)

fclean:
	rm -f $(lahcen) $(OBJ)

re: fclean all clean

.PHONY: all re clean fclean
